image: maven
before_script:
- mvn install
- wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
- chmod +x default
- ./default -V

stages:
 - build
 - deploy

build:
  stage: build
  script:
    - mvn install
    - mvn clean
    - mvn package
    - tar -cvf AsciiRogue.tar target/*.jar
    - zip AsciiRogue target/*.jar
  artifacts:
    paths:
    - AsciiRogue.tar
    - AsciiRogue.zip
deploy:
  stage: deploy
  script:
    - ./default -V
    - default push AsciiRogue.tar Dev-Osmium/AsciiRogue:latest
  only:
    - master
